<?php


namespace BlueYetchy\LibCore\Providers;


use Illuminate\Support\ServiceProvider;

class LibCoreServiceProvider extends ServiceProvider
{
    public function register()
    {
        parent::register(); // TODO: Change the autogenerated stub
    }
}